### ISSUE TITLE
Error on start with Debian 11, and Fedora 38

### ISSUE THREAD

**Issue by 314159-r** [enteropositivo/seedsigner-emulator#7]
I have installed according your instructions on Debian 11 without issues. 
But when I try to start the emulator, I get this error:
```user@disp979:~/git/seedsigner/src$ python3 main.py
Traceback (most recent call last):
  File "/home/user/git/seedsigner/src/main.py", line 1, in <module>
    from seedsigner.controller import Controller
  File "/home/user/git/seedsigner/src/seedsigner/controller.py", line 8, in <module>
    from seedsigner.models.settings import Settings
  File "/home/user/git/seedsigner/src/seedsigner/models/settings.py", line 7, in <module>
    from seedsigner.models.settings_definition import SettingsConstants, SettingsDefinition
  File "/home/user/git/seedsigner/src/seedsigner/models/settings_definition.py", line 203, in <module>
    class SettingsEntry:
  File "/home/user/git/seedsigner/src/seedsigner/models/settings_definition.py", line 223, in SettingsEntry
    selection_options: list[tuple[str | int], str] = None
TypeError: unsupported operand type(s) for |: 'type' and 'type'
```
.
On Fedora some "apt" (dnf) packages have different names, so I made some guesses witch seemed to work:

- python3-tk --> python3-tkinter
- libzbar0 --> python3-zbar (includes: zbar-libs)

But for the last 3 pip installs, I got these "deprecation" warnings:
```[user@disp542 src]$ pip3 install git+https://github.com/jreesun/urtypes.git@e0d0db277ec2339650343eaf7b220fffb9233241
Defaulting to user installation because normal site-packages is not writeable
Collecting git+https://github.com/jreesun/urtypes.git@e0d0db277ec2339650343eaf7b220fffb9233241
  Cloning https://github.com/jreesun/urtypes.git (to revision e0d0db277ec2339650343eaf7b220fffb9233241) to /tmp/pip-req-build-xihwtrfv
  Running command git clone --filter=blob:none --quiet https://github.com/jreesun/urtypes.git /tmp/pip-req-build-xihwtrfv
  Running command git rev-parse -q --verify 'sha^e0d0db277ec2339650343eaf7b220fffb9233241'
  Running command git fetch -q https://github.com/jreesun/urtypes.git e0d0db277ec2339650343eaf7b220fffb9233241
  Running command git checkout -q e0d0db277ec2339650343eaf7b220fffb9233241
  Resolved https://github.com/jreesun/urtypes.git to commit e0d0db277ec2339650343eaf7b220fffb9233241
  Preparing metadata (setup.py) ... done
Installing collected packages: urtypes
  DEPRECATION: urtypes is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for urtypes ... done
Successfully installed urtypes-0.1.0
[user@disp542 src]$ pip3 install git+https://github.com/enteropositivo/pyzbar.git@a52ff0b2e8ff714ba53bbf6461c89d672a304411#egg=pyzbar
Defaulting to user installation because normal site-packages is not writeable
Collecting pyzbar
  Cloning https://github.com/enteropositivo/pyzbar.git (to revision a52ff0b2e8ff714ba53bbf6461c89d672a304411) to /tmp/pip-install-8teg8l0q/pyzbar_b848bc07266944098d3d3dd1b270c9b2
  Running command git clone --filter=blob:none --quiet https://github.com/enteropositivo/pyzbar.git /tmp/pip-install-8teg8l0q/pyzbar_b848bc07266944098d3d3dd1b270c9b2
  Running command git rev-parse -q --verify 'sha^a52ff0b2e8ff714ba53bbf6461c89d672a304411'
  Running command git fetch -q https://github.com/enteropositivo/pyzbar.git a52ff0b2e8ff714ba53bbf6461c89d672a304411
  Resolved https://github.com/enteropositivo/pyzbar.git to commit a52ff0b2e8ff714ba53bbf6461c89d672a304411
  Preparing metadata (setup.py) ... done
Installing collected packages: pyzbar
  DEPRECATION: pyzbar is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for pyzbar ... done
Successfully installed pyzbar-0.1.9
[user@disp542 src]$ pip3 install embit dataclasses qrcode tk opencv-python
Defaulting to user installation because normal site-packages is not writeable
Collecting embit
  Downloading embit-0.7.0.tar.gz (755 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 755.0/755.0 kB 12.0 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dataclasses
  Downloading dataclasses-0.6-py3-none-any.whl (14 kB)
Collecting qrcode
  Downloading qrcode-7.4.2-py3-none-any.whl (46 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 46.2/46.2 kB 3.2 MB/s eta 0:00:00
Collecting tk
  Downloading tk-0.1.0-py3-none-any.whl (3.9 kB)
Collecting opencv-python
  Downloading opencv_python-4.8.1.78-cp37-abi3-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (61.7 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 61.7/61.7 MB 17.5 MB/s eta 0:00:00
Collecting typing-extensions
  Downloading typing_extensions-4.8.0-py3-none-any.whl (31 kB)
Collecting pypng
  Downloading pypng-0.20220715.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.1/58.1 kB 4.1 MB/s eta 0:00:00
Requirement already satisfied: numpy>=1.21.2 in /usr/lib64/python3.11/site-packages (from opencv-python) (1.24.4)
Installing collected packages: tk, pypng, embit, dataclasses, typing-extensions, opencv-python, qrcode
  DEPRECATION: embit is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559
  Running setup.py install for embit ... done
Successfully installed dataclasses-0.6 embit-0.7.0 opencv-python-4.8.1.78 pypng-0.20220715.0 qrcode-7.4.2 tk-0.1.0 typing-extensions-4.8.0
```
And when I try to start the emulator, I get a different error:
```[user@disp542 src]$ python3 main.py
Traceback (most recent call last):
  File "/home/user/Hämtningar/seedsigner/src/main.py", line 1, in <module>
    from seedsigner.controller import Controller
  File "/home/user/Hämtningar/seedsigner/src/seedsigner/controller.py", line 11, in <module>
    from seedsigner.views.view import Destination
  File "/home/user/Hämtningar/seedsigner/src/seedsigner/views/__init__.py", line 1, in <module>
    from .view import *  # base class has to be first
    ^^^^^^^^^^^^^^^^^^^
  File "/home/user/Hämtningar/seedsigner/src/seedsigner/views/view.py", line 4, in <module>
    from seedsigner.gui.components import FontAwesomeIconConstants, SeedSignerIconConstants
  File "/home/user/Hämtningar/seedsigner/src/seedsigner/gui/__init__.py", line 1, in <module>
    from .renderer import Renderer
  File "/home/user/Hämtningar/seedsigner/src/seedsigner/gui/renderer.py", line 7, in <module>
    from seedsigner.models import ConfigurableSingleton
ImportError: cannot import name 'ConfigurableSingleton' from 'seedsigner.models' (/home/user/Hämtningar/seedsigner/src/seedsigner/models/__init__.py)
```

This might be an edge case, as both Debian and Fedora runs as virtual machines in a Qubes OS system.

**Comment by 314159-r** [comment]
The emulator don't work with the latest version of SeedSigner v0.7.0
I can install and run the simulator with SeedSigner version 0.5.1 or 0.6.0 on Debian 11 (not tested with Fedora though).

Closing this issue

**Comment by 314159-r** [comment]
Closing this issue.
