### ISSUE TITLE
Emulator don't work with SeedSigner v.0.7.0

### ISSUE THREAD

**Issue by 314159-r** [enteropositivo/seedsigner-emulator#8]
The emulator works with SeedSigner version up to v.0.6.0, but not with v.0.7.0

When starting main.py, it responds with this error:
```
Traceback (most recent call last):
  File "/home/user/git/seedsigner/src/main.py", line 1, in <module>
    from seedsigner.controller import Controller
  File "/home/user/git/seedsigner/src/seedsigner/controller.py", line 8, in <module>
    from seedsigner.models.settings import Settings
  File "/home/user/git/seedsigner/src/seedsigner/models/settings.py", line 7, in <module>
    from seedsigner.models.settings_definition import SettingsConstants, SettingsDefinition
  File "/home/user/git/seedsigner/src/seedsigner/models/settings_definition.py", line 203, in <module>
    class SettingsEntry:
  File "/home/user/git/seedsigner/src/seedsigner/models/settings_definition.py", line 223, in SettingsEntry
    selection_options: list[tuple[str | int], str] = None
TypeError: unsupported operand type(s) for |: 'type' and 'type'

**Comment by tadeubas** [comment]
It is working now. The only problem I've found on Windows 11 with Python 3.12 was this:
`ValueError: mutable default <class 'seedsigner.views.view.Destination'> for field next_destination is not allowed: use default_factory`

I had to edit the file `seedsigner\src\seedsigner\views\view.py` (from seedsigner) and change the line 314: `next_destination: Destination = Destination(MainMenuView, clear_history=True)` to `next_destination: Destination = None`
